### ISSUE TITLE
EmailVenrify不支持outlook邮箱？

### ISSUE THREAD

**Issue by DJRsiri** [CatSeed/CatSeedLogin#33]
正确输入账户密码后，当SSLAuthVerify为true时
【
[14:56:56 INFO]: [CatSeedLogin] [STDOUT] DEBUG: setDebug: JavaMail version 1.5.0-b01
[14:56:56 WARN]: Nag author(s): '[CatSeed]' of 'CatSeedLogin v1.3.10-SNAPSHOT' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[14:56:56 INFO]: [CatSeedLogin] [STDOUT] DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
[14:56:56 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: useEhlo true, useAuth true
[14:56:56 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: trying to connect to host "smtp-mail.outlook.com", port 587, isSSL false
[14:56:56 WARN]: javax.mail.MessagingException: Could not connect to SMTP host: smtp-mail.outlook.com, port: 587;
[14:56:56 WARN]:   nested exception is:
[14:56:56 WARN]:        javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
[14:56:56 WARN]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1961)
[14:56:56 WARN]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:654)
[14:56:56 WARN]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//javax.mail.Service.connect(Service.java:295)
[14:56:56 WARN]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//javax.mail.Service.connect(Service.java:176)
[14:56:56 WARN]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//javax.mail.Service.connect(Service.java:196)
[14:56:56 WARN]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//cc.baka9.catseedlogin.util.Mail.sendMail(Mail.java:54)
[14:56:56 WARN]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//cc.baka9.catseedlogin.command.CommandBindEmail.lambda$onCommand$2(CommandBindEmail.java:59)
[14:56:56 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[14:56:56 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[14:56:56 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:56:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[14:56:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[14:56:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[14:56:56 WARN]: Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
[14:56:56 WARN]:        at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:162)
[14:56:56 WARN]:        at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
[14:56:56 WARN]:        at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:247)
[14:56:56 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:448)
[14:56:56 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
[14:56:56 WARN]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:527)
[14:56:56 WARN]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:332)
[14:56:56 WARN]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:208)
[14:56:56 WARN]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1927)
[14:56:56 WARN]:        ... 12 more
】
为false时提示：
【
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG: setDebug: JavaMail version 1.5.0-b01
[14:53:38 WARN]: Nag author(s): '[CatSeed]' of 'CatSeedLogin v1.3.10-SNAPSHOT' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: useEhlo true, useAuth true
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: trying to connect to host "smtp-mail.outlook.com", port 587, isSSL false
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] 220 SG2PR04CA0152.outlook.office365.com Microsoft ESMTP MAIL Service ready at Sun, 27 Oct 2024 06:53:37 +0000 [08DCF5F5C8E24D90]
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: connected to host "smtp-mail.outlook.com", port: 587

[14:53:38 INFO]: [CatSeedLogin] [STDOUT] EHLO DESKTOP-1VQ28PL
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250-SG2PR04CA0152.outlook.office365.com Hello [27.152.208.153]
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250-SIZE 157286400
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250-PIPELINING
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250-DSN
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250-ENHANCEDSTATUSCODES
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250-STARTTLS
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250-8BITMIME
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250-BINARYMIME
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250-CHUNKING
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250 SMTPUTF8
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: Found extension "SIZE", arg "157286400"
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: Found extension "PIPELINING", arg ""
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: Found extension "DSN", arg ""
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: Found extension "ENHANCEDSTATUSCODES", arg ""
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: Found extension "STARTTLS", arg ""
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: Found extension "8BITMIME", arg ""
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: Found extension "BINARYMIME", arg ""
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: Found extension "CHUNKING", arg ""
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: Found extension "SMTPUTF8", arg ""
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: use8bit false
[14:53:38 INFO]: [CatSeedLogin] [STDOUT] MAIL FROM:<*邮箱地址[隐藏]*>
[14:53:43 INFO]: [CatSeedLogin] [STDOUT] 451 5.7.3 STARTTLS is required to send mail [SG2PR04CA0152.apcprd04.prod.outlook.com 2024-10-27T06:53:43.584Z 08DCF5F5C8E24D90]
[14:53:43 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: got response code 451, with response: 451 5.7.3 STARTTLS is required to send mail [SG2PR04CA0152.apcprd04.prod.outlook.com 2024-10-27T06:53:43.584Z 08DCF5F5C8E24D90]

[14:53:43 INFO]: [CatSeedLogin] [STDOUT] RSET
[14:53:43 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: EOF: [EOF]
[14:53:43 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: MessagingException while sending, THROW:
[14:53:43 INFO]: com.sun.mail.smtp.SMTPSendFailedException: 451 5.7.3 STARTTLS is required to send mail [SG2PR04CA0152.apcprd04.prod.outlook.com 2024-10-27T06:53:43.584Z 08DCF5F5C8E24D90]
[14:53:43 INFO]:
[14:53:43 INFO]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2108)
[14:53:43 INFO]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1609)
[14:53:43 INFO]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1117)
[14:53:43 INFO]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//cc.baka9.catseedlogin.util.Mail.sendMail(Mail.java:55)
[14:53:43 INFO]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//cc.baka9.catseedlogin.command.CommandBindEmail.lambda$onCommand$2(CommandBindEmail.java:59)
[14:53:43 INFO]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[14:53:43 INFO]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[14:53:43 INFO]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:53:43 INFO]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[14:53:43 INFO]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[14:53:43 INFO]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[14:53:43 WARN]: com.sun.mail.smtp.SMTPSendFailedException: 451 5.7.3 STARTTLS is required to send mail [SG2PR04CA0152.apcprd04.prod.outlook.com 2024-10-27T06:53:43.584Z 08DCF5F5C8E24D90]
[14:53:43 WARN]:
[14:53:43 WARN]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2108)
[14:53:43 WARN]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1609)
[14:53:43 WARN]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1117)
[14:53:43 WARN]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//cc.baka9.catseedlogin.util.Mail.sendMail(Mail.java:55)
[14:53:43 WARN]:        at CatSeedLogin-1.3.10-SNAPSHOT.jar//cc.baka9.catseedlogin.command.CommandBindEmail.lambda$onCommand$2(CommandBindEmail.java:59)
[14:53:43 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[14:53:43 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[14:53:43 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:53:43 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[14:53:43 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[14:53:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
】
outlook smtp文档：
https://support.microsoft.com/zh-cn/office/outlook-com-%E7%9A%84-pop-imap-%E5%92%8C-smtp-%E8%AE%BE%E7%BD%AE-d088b986-291d-42b8-9564-9c414e2aa040

**Comment by shulng** [comment]
> 正确输入账户密码后，当SSLAuthVerify为true时 【 [14:56:56 INFO]: [CatSeedLogin] [STDOUT] DEBUG: setDebug: JavaMail version 1.5.0-b01 [14:56:56 WARN]: Nag author(s): '[CatSeed]' of 'CatSeedLogin v1.3.10-SNAPSHOT' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger). [14:56:56 INFO]: [CatSeedLogin] [STDOUT] DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle] [14:56:56 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: useEhlo true, useAuth true [14:56:56 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: trying to connect to host "smtp-mail.outlook.com", port 587, isSSL false [14:56:56 WARN]: javax.mail.MessagingException: Could not connect to SMTP host: smtp-mail.outlook.com, port: 587; [14:56:56 WARN]: nested exception is: [14:56:56 WARN]: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate) [14:56:56 WARN]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1961) [14:56:56 WARN]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:654) [14:56:56 WARN]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//javax.mail.Service.connect(Service.java:295) [14:56:56 WARN]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//javax.mail.Service.connect(Service.java:176) [14:56:56 WARN]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//javax.mail.Service.connect(Service.java:196) [14:56:56 WARN]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//cc.baka9.catseedlogin.util.Mail.sendMail(Mail.java:54) [14:56:56 WARN]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//cc.baka9.catseedlogin.command.CommandBindEmail.lambda$onCommand$2(CommandBindEmail.java:59) [14:56:56 WARN]: at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) [14:56:56 WARN]: at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [14:56:56 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [14:56:56 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [14:56:56 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [14:56:56 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583) [14:56:56 WARN]: Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate) [14:56:56 WARN]: at java.base/sun.security.ssl.HandshakeContext.(HandshakeContext.java:162) [14:56:56 WARN]: at java.base/sun.security.ssl.ClientHandshakeContext.(ClientHandshakeContext.java:103) [14:56:56 WARN]: at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:247) [14:56:56 WARN]: at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:448) [14:56:56 WARN]: at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426) [14:56:56 WARN]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:527) [14:56:56 WARN]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:332) [14:56:56 WARN]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:208) [14:56:56 WARN]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1927) [14:56:56 WARN]: ... 12 more 】 为false时提示： 【 [14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG: setDebug: JavaMail version 1.5.0-b01 [14:53:38 WARN]: Nag author(s): '[CatSeed]' of 'CatSeedLogin v1.3.10-SNAPSHOT' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger). [14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle] [14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: useEhlo true, useAuth true [14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: trying to connect to host "smtp-mail.outlook.com", port 587, isSSL false [14:53:38 INFO]: [CatSeedLogin] [STDOUT] 220 SG2PR04CA0152.outlook.office365.com Microsoft ESMTP MAIL Service ready at Sun, 27 Oct 2024 06:53:37 +0000 [08DCF5F5C8E24D90] [14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: connected to host "smtp-mail.outlook.com", port: 587
> 
> [14:53:38 INFO]: [CatSeedLogin] [STDOUT] EHLO DESKTOP-1VQ28PL [14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250-SG2PR04CA0152.outlook.office365.com Hello [27.152.208.153] [14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250-SIZE 157286400 [14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250-PIPELINING [14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250-DSN [14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250-ENHANCEDSTATUSCODES [14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250-STARTTLS [14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250-8BITMIME [14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250-BINARYMIME [14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250-CHUNKING [14:53:38 INFO]: [CatSeedLogin] [STDOUT] 250 SMTPUTF8 [14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: Found extension "SIZE", arg "157286400" [14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: Found extension "PIPELINING", arg "" [14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: Found extension "DSN", arg "" [14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: Found extension "ENHANCEDSTATUSCODES", arg "" [14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: Found extension "STARTTLS", arg "" [14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: Found extension "8BITMIME", arg "" [14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: Found extension "BINARYMIME", arg "" [14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: Found extension "CHUNKING", arg "" [14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: Found extension "SMTPUTF8", arg "" [14:53:38 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: use8bit false [14:53:38 INFO]: [CatSeedLogin] [STDOUT] MAIL FROM:<_邮箱地址[隐藏]_> [14:53:43 INFO]: [CatSeedLogin] [STDOUT] 451 5.7.3 STARTTLS is required to send mail [SG2PR04CA0152.apcprd04.prod.outlook.com 2024-10-27T06:53:43.584Z 08DCF5F5C8E24D90] [14:53:43 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: got response code 451, with response: 451 5.7.3 STARTTLS is required to send mail [SG2PR04CA0152.apcprd04.prod.outlook.com 2024-10-27T06:53:43.584Z 08DCF5F5C8E24D90]
> 
> [14:53:43 INFO]: [CatSeedLogin] [STDOUT] RSET [14:53:43 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: EOF: [EOF] [14:53:43 INFO]: [CatSeedLogin] [STDOUT] DEBUG SMTP: MessagingException while sending, THROW: [14:53:43 INFO]: com.sun.mail.smtp.SMTPSendFailedException: 451 5.7.3 STARTTLS is required to send mail [SG2PR04CA0152.apcprd04.prod.outlook.com 2024-10-27T06:53:43.584Z 08DCF5F5C8E24D90] [14:53:43 INFO]: [14:53:43 INFO]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2108) [14:53:43 INFO]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1609) [14:53:43 INFO]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1117) [14:53:43 INFO]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//cc.baka9.catseedlogin.util.Mail.sendMail(Mail.java:55) [14:53:43 INFO]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//cc.baka9.catseedlogin.command.CommandBindEmail.lambda$onCommand$2(CommandBindEmail.java:59) [14:53:43 INFO]: at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) [14:53:43 INFO]: at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [14:53:43 INFO]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [14:53:43 INFO]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [14:53:43 INFO]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [14:53:43 INFO]: at java.base/java.lang.Thread.run(Thread.java:1583) [14:53:43 WARN]: com.sun.mail.smtp.SMTPSendFailedException: 451 5.7.3 STARTTLS is required to send mail [SG2PR04CA0152.apcprd04.prod.outlook.com 2024-10-27T06:53:43.584Z 08DCF5F5C8E24D90] [14:53:43 WARN]: [14:53:43 WARN]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2108) [14:53:43 WARN]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1609) [14:53:43 WARN]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1117) [14:53:43 WARN]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//cc.baka9.catseedlogin.util.Mail.sendMail(Mail.java:55) [14:53:43 WARN]: at CatSeedLogin-1.3.10-SNAPSHOT.jar//cc.baka9.catseedlogin.command.CommandBindEmail.lambda$onCommand$2(CommandBindEmail.java:59) [14:53:43 WARN]: at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) [14:53:43 WARN]: at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [14:53:43 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [14:53:43 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [14:53:43 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [14:53:43 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583) 】 outlook smtp文档： https://support.microsoft.com/zh-cn/office/outlook-com-%E7%9A%84-pop-imap-%E5%92%8C-smtp-%E8%AE%BE%E7%BD%AE-d088b986-291d-42b8-9564-9c414e2aa040

去用社区维护版[CatSeedLogin](https://github.com/zhinghu/CatSeedLogin/releases/latest)
